language: ruby
bundler_args: --without development
rvm:
  - 2.0.0
before_script:
  - "psql -c 'create database myapp_test;' -U postgres"
  - 'cp config/database.yml.example config/database.yml'
  - 'cp config/application.example.yml config/application.yml'
  - 'rake db:test:load'
script: 'bundle exec rake spec'
