secret_token: 'change-me'
secret_key_base : 'change-me'

development:
  mailer:
    delivery_method: 'smtp'
    raise_delivery_errors: 'false'

    default_options:
      host: 'localhost:3000'

    smtp_settings:
      domain: 'smtp.mail_exemple.com'
      authentication: 'plain'
      user_name: 'user_name'
      password: 'password'

test:
  mailer:
    default_options:
      host: 'localhost:3000'

    smtp_settings:
      delivery_method: 'test'

production:
  mailer:
    delivery_method: 'smtp'
    raise_delivery_errors: 'false'

    default_options:
      host: 'website_domain.com'

    smtp_settings:
      domain: 'smtp.mail_exemple.com'
      authentication: 'plain'
      user_name: 'user_name'
      password: 'password'
