secret_token: '886717c8966a267d1412097cb47b782154542ab062ef8225c3cfe20f4866b1de2f3853693203ee31aedc9ca1adc0da52d744a710151879b94e567425459c2214'

development:
  mailer:
    delivery_method: 'smtp'
    raise_delivery_errors: 'false'

    default_options:
      host: 'localhost:3000'

    smtp_settings:
      domain: 'smtp.mail_exemple.com'
      authentication: 'plain'
      user_name: 'user_name'
      password: 'password'

test:
  mailer:
    default_options:
      host: 'localhost:3000'

    smtp_settings:
      delivery_method: 'test'

production:
  mailer:
    delivery_method: 'smtp'
    raise_delivery_errors: 'false'

    default_options:
      host: 'website_domain.com'

    smtp_settings:
      domain: 'smtp.mail_exemple.com'
      authentication: 'plain'
      user_name: 'user_name'
      password: 'password'