secret_token: 'change-me'
secret_key_base : 'change-me'

development:
  action_mailer:
    delivery_method: :smtp
    raise_delivery_errors: true

    default_url_options:
      :host: 'localhost:3000'

    smtp_settings:
      :address:              'smtp.exemple.com'
      :domain:               'exemple.com'
      :port:                 25
      :authentication:       'plain'
      :enable_starttls_auto: false
      :user_name:            'username'
      :password:             'password'

test:
  action_mailer:
    default_url_options:
      :host: 'localhost:3000'

    smtp_settings:
      delivery_method: :test

production:
  action_mailer:
    delivery_method: :smtp
    raise_delivery_errors: false

    default_url_options:
      :host: 'localhost:3000'

    smtp_settings:
      :address:              'smtp.exemple.com'
      :domain:               'exemple.com'
      :port:                 25
      :authentication:       'plain'
      :enable_starttls_auto: false
      :user_name:            'username'
      :password:             'password'


