common: &common
  adapter: mysql
  encoding: utf8
  reconnect: false
  pool: 5
  username: Boutique
  password: x2c3z4r8
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *common
  database: Boutique_dev

production:
  <<: *common
  database: Boutique

test: &test
  <<: *common
  database: Boutique_test
